language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    - build-tools-29.0.2
    - android-29

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - ./gradlew test
