language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    - build-tools-30.0.2
    - android-30

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - cd project
  - ./gradlew test
