language: android

jdk: oraclejdk8

sudo: false

android:
  components:
    - build-tools-27.0.3
    - android-28

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - gradle build connectedCheck
