name: test
on:
  push:
    branches:
      - '*'

jobs:
  build-app:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test with Gradle
        run: cd project; ./gradlew test